web/router.ex
defmodule Rallychat.Router do
  use Rallychat.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Rallychat.Auth, repo: Rallychat.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Rallychat do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    #move to protected route eventualy
    resources "/lobby", RallyController, only: [:index, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Rallychat do
  #   pipe_through :api
  # end
end

lib/rallychat/endpoint.ex
defmodule Rallychat.Endpoint do
  use Phoenix.Endpoint, otp_app: :rallychat

  socket "/socket", Rallychat.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :rallychat, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_rallychat_key",
    signing_salt: "+qqF1ycf"

  plug Rallychat.Router
end

lib/rallychat/repo.ex
defmodule Rallychat.Repo do
  use Ecto.Repo, otp_app: :rallychat
end

lib/rallychat/tweet_streamer.ex
defmodule Rallychat.TwitterStreamer do
    
    def start(socket, query) do
        stream = ExTwitter.stream _filter(track: query)

    for tweet <- stream do 
        Phoneix.Channel.reply(socket, "tweet:stream", tweet)
    end
end
end

web/models/message.ex
defmodule Rallychat.Message do
  use Rallychat.Web, :model

  schema "messages" do
    field :body, :string
    belongs_to :user, Rallychat.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body])
    |> validate_required([:body])
#    TODO validate message lenghts, etc
  end
end

web/models/user.ex
defmodule Rallychat.User do
    use Rallychat.Web, :model

    schema "users" do
        field :name, :string
        field :username, :string
        field :password, :string, virtual: true
        field :password_hash, :string
        
        timestamps()
    end
    
    def changeset(model, params \\ :empty) do
        model
        |> cast(params, ~w(name username), [])
        |> validate_length(:username, min: 1, max: 20)
    end
end

web/models/users.ex
defmodule Rallychat.User do
  use Rallychat.Web, :model


  schema "users" do
    field :name, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps()
  end


  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:name])
    |> validate_required([:name])
    |> validate_length(:name, min: 1, max: 10)
    |> unique_constraint(:name)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> cast(params, [:password])
    |> validate_length(:password, min: 6, max: 100)
    |> put_pass_hash()
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
        _ -> changeset
    end
  end
end

web/controllers/page_controller.ex
defmodule Rallychat.PageController do
  use Rallychat.Web, :controller

  def index(conn, _params) do
   redirect(conn, to: rally_path(conn, :index))
  end

  # def index(conn, params) do
  #   redirect(conn, to: "/users/new")
  # end
end

web/controllers/rally_controller.ex
defmodule Rallychat.RallyController do
  use Rallychat.Web, :controller

  alias Rallychat.Message

  #auth plug probs

  def index(conn, _params) do
    changeset = Message.changeset(%Message{})
    render conn, "index.html", changeset: changeset
  end

  def create(conn, _params) do
    #no functionality yet
    changeset = Message.changeset(%Message{})
    #probs not correct
    render conn, "index.html", changeset: changeset 
  end
end

web/controllers/session_controller.ex
defmodule Rallychat.SessionController do
  use Rallychat.Web, :controller


  def new(conn, _) do
    render conn, "new.html"
  end


  def create(conn, %{"session" => %{"name" => name, "password" => pass}} = params) do
    case Rallychat.Auth.login_by_username_pass(conn, name, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "welcome back")
        |> redirect(to: rally_path(conn, :index))

      {:error, _, conn} ->
        conn
        |> put_flash(:error, "invalid username/password combination")
        |> render("new.html")
    end
  end


  def delete(conn, _) do
    conn
    |> Rallychat.Auth.logout()
    |> redirect(to: page_path(conn, :index))
  end
end

web/controllers/user_controller.ex
defmodule Rallychat.UserController do
  use Rallychat.Web, :controller

  alias Rallychat.User

  plug :authenticate_user when action in [:index, :show]

  
  def index(conn, _params) do
    users = Repo.all(User)
    render  conn, "index.html", users: users
  end


  def show(conn, %{"id" => id}) do
    user = Repo.get(User, id)
    render conn, "show.html", user: user
  end


  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end


  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> Rallychat.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: rally_path(conn, :index))
        
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

web/views/error_view.ex
defmodule Rallychat.ErrorView do
  use Rallychat.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Rallychat.LayoutView do
  use Rallychat.Web, :view
end

web/views/page_view.ex
defmodule Rallychat.PageView do
  use Rallychat.Web, :view
end

web/views/rally_view.ex
defmodule Rallychat.RallyView do
  use Rallychat.Web, :view
end

web/views/session_view.ex
defmodule Rallychat.SessionView do
  use Rallychat.Web, :view
end

web/views/user_view.ex
defmodule Rallychat.UserView do
  use Rallychat.Web, :view
  alias Rallychat.User

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width", intial-scale="1", maximum-scale="1">
    <title>bRallychat!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    
  </head>

  <body>
    <div class="container">
      <header class="header">
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://platform.twitter.com/widgets.js"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

web/templates/page/schedule.html.eex
<!--workshop scheudle-->
<div>
The Honolulu Theatre for Youth and The Sex Abuse Treatment Center present the Fourth Annual Rally for [respect]! This year the rally will be held on Saturday, April 1st to help kick off Sexual Assault Awareness Month.

High Schoolers Unite! This event is for high school teenagers across Hawaii!

We invite high school teenagers to join in and participate in new workshops, with new speakers and new opportunities for participants to use their voice and talent to help us all build a culture of [respect] in our communities across our beautiful islands.

If you have a group you would like to perform at the rally please contact the event organizer for more details on how to make that happen. We are looking for dynamic youth groups to use their talent to help energize this movement toward standing up for [respect] in our communities.

Rally for [respect] - April 1, 2017:

1:30 - Opening and welcome.

2:30 - 4:30 - Workshops with some of Hawaii's leading artists in their fields.

4:30 - 5:30 - Dinner (FREE FOOD for workshop participants!)

5:30 - Rally begins!

Space is limited - sign up today!!!
</div>

web/templates/page/workshops.html.eex
<!--workshop leaders-->

George Kon
Theatre
George Kon is the Co-Founder & Executive Director of Alliance for Drama Education and Artistic Director of T-Shirt Theatre where he has staged 75 shows with over 1,000 talented Kalihi kids. He has traveled around the world as both a performer and educator and has received numerous awards including, most recently, the KALAMA AWARD for “Excellence in Perpetuating the Arts and Culture in Hawaii.”
Jonah Moananu
Rap
Jonah Moananu - aka “bigMOX” is an Artist Educator, songwriter, and vocal recording artist specializing in singing and rapping. He has been a Teaching Artist with the Alliance for Drama Education for 15 years, creating innovative curriculum for grades K-12 having taught at public and private schools across the state. 1/4 of the “Angry Locals,”, 1/2 of the “Prolific Unknowns”, as well as lead vocals for the Jedi jazz collective “theBentos”. Reigning undefeated “island freestyle rap” champion, and 3rd season of American Idol semi-finalist.
Harmony Turner
Dance
Harmony Sayward Turner - Dancer, yogi, and educator, Harmony Turner, has an incredible passion for movement arts, education, and youth. Alongside a BA in Theatre Arts and MFA in Dance, Harmony is also a Yoga Ed. Trainer and Educator (PK-12) for Honolulu, Hawaii. She has immersed herself in the field of education and is on her way to achieving a Masters in Teaching for the Elementary grades. Harmony has had the privilege to share her love for dance and theatre with diverse and influential organizations, including Honolulu Theatre for Youth, Manoa Valley Theatre, and the East West Center. In 2013, Harmony founded her own dance, yoga, and education company: HarmsaStar. With goals of artistic expression, integrity, community, and collaboration, Harmony is beyond enthusiastic for every opportunity that comes her way. 
Rumi Murakami
Fashion
Rumi Murakami - at an early age, Rumi spent hours poring over her mother’s Bazaar magazines and recreating designs using makeshift patterns and an old Singer. A graduate of the Fashion Institute of Design and Merchandising, her creative voice developed out of her work in the garment industry in Los Angeles and San Francisco. Influenced deeply by her Japanese heritage as well as her love of urban environments, Rumi’s designs strike a balance between tradition and modernity, function and beauty. She is currently designer & owner of rumi murakami, a women’s clothing brand based in Honolulu. As a domestic violence survivor, Rumi is a dedicated advocate and activist for social justice. She has worked with adult survivors and child-victim/witnesses of intimate partner violence as a counselor and with the Hawaii State Legislature advocating and educating lawmakers about how to strengthen victim rights and offender accountability. In order to bring balance to her days, Rumi practices yoga and spends time with her loved ones, furry and otherwise.
Su Atta
Creative Arts Experience
Su Atta is the volunteer executive director for Creative Arts Experience (CAE) and comes with years of experience as a professional artist as well as an art educator. She loves making art fun and engaging. CAE is a non-profit organization whose goal is to bring art activities and creative experiences to folks of all ages.We believe that EVERYONE is an artist. And, ART is LIFE. So, we want people to come play, splash paint, doodle, hum, make marks because it feels good. Perhaps, in the end, through the creative process, you may come up with a better idea about yourself, life or the world.
Darron Cambra
Slam Poetry
This workshop will feature techniques to release the inner wordsmith. Any writing/ reading level welcomed. In Da Pen Dance’s goal is to guide writers in techniques to overcome the vastness of a blank page or screen as a place of endless possibilities, rather than a void of confusion. Hosted by Darron Cambra- Teacher/Performer/Poet 
Jonathan Sypert
Lyrical Hip Hop
 Jonathan teaches singing, dancing, acting, poetry, rap and music production for a variety of organizations including Henry J. Kaiser High School, Hawaii Opera Theatre, Honolulu Theatre for Youth, PALS/PLACES on the Waianae Coast, The Clarence T.C. Ching PUEO Program at Punahou School, STEPS to Success with Ohana Komputer, and Pacific Tongues. Jonathan uses his talents and connections to build partnerships with charities and organizations that are entrenched in the front lines of social causes and issues. In 2017 Jonathan will be involved with the Sex Abuse Treatment center of Honolulu and Honolulu Theatre for Youth for the respect 2.0 interscholastic rally; pacific tongues' interscholastic poetry workshops; organize entertainment for events to benefit the Kapiolani Medical Center for Women and Children; will host a YouTube channel to reveal "What's Poppin" in the culture and arts of the Aloha State; and will co-design an online marketing strategy for FASD Communities, a not-for-profit organization that is laying the foundation for a network of rehabilitative residencies for adults afflicted with Fetal Alcohol Spectrum Disorder.
Primo Asis
Parent/Teacher workshop
 Primo Asis , Who says the students should have all the fun? In this workshop, parents and teachers will learn some creative ways for connecting with their students and addressing difficult issues. 
Music 
TBA

Culture or Film
TBA

web/templates/rally/index.html.eex
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>oops, check errors below.</p>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      
      
      <div id="messages" height="600" position="fixed"></div>

      <div id="footer">
        <input id="chat-input" type="text"></input>
      </div>
      
    </div>
    <div class="col-xs-6">
      <div class="container-fluid">
        
        <iframe src='https://www.juicer.io/api/feeds/respecthawaii/iframe' frameborder='0' width='600' height='600' style='display:block;margin:0 auto;'></iframe>
      </div>
    </div>
  </div>
</div>

web/templates/session/new.html.eex
<h1>Login</h1>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
<div class="form-group">
  <%= text_input f, :name, placeholder: "username", class: "form-control" %>
</div>
<div class="form-group">
  <%= password_input f, :password, placeholder: "password", class: "form-control" %>
</div>
<%= submit "Log in", class: "btn btn-primarya" %>
<% end %>

web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table class="table">
  <%= for user <- @users do %>
    <tr>
      <td><%= render "user.html", user: user %></td>
      <td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
    </tr>
  <% end %>
</table>

web/templates/user/new.html.eex
<h1>New user</h1>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, check errors below.</p>
  </div>
<% end %>

<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
<div class="form-group">
  <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
  <%= error_tag f, :name %>
</div>
<div class="form-group">
  <%= password_input f, :password, placeholder: "Pasword", class: "form-control" %>
  <%= error_tag f, :passowrd %>
</div>
<%= submit "Create User", class: "btn btn-primary" %>
<% end %>

web/templates/user/show.html.eex
<h1>Showing User</h1>
<%= render "user.html", user: @user %>

web/templates/user/stats.html.eex
<!--stats in the chatroom-->

web/templates/user/user.html.eex
<b><%=  @user.name %></b> (<%=  @user.id %>)